"use client";

import { motion } from "framer-motion";
import { ServicesVoyageSlider } from "@/components/ServicesVoyageSlider";
import { FeatureShowcase, type TabMedia } from "@/components/ui/feature-showcase";
import { homeSectionReveal } from "@/lib/home-section-motion";
import { useLocaleContext } from "@/lib/i18n/locale-context";

type HomeServicesSectionProps = {
  /** `home`: in-page `#services` anchor. `standalone`: dedicated route (no id). */
  variant?: "home" | "standalone";
};

const selectedProjectTabs: TabMedia[] = [
  {
    value: "grand-finance",
    label: "Borrower Portal",
    src: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=85",
    alt: "Unified borrower data portal — Grand Finance Group",
  },
  {
    value: "wilson-cpa",
    label: "CPA Workspace",
    src: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=85",
    alt: "Compliance intelligence workspace — LKKS CPA Limited",
  },
];

const projectSteps = [
  {
    id: "grand-finance",
    title: "Unified Borrower Intelligence Portal — Grand Finance Group",
    text: "Grand Finance operated across five disconnected loan management systems with no shared search layer. Loan officers spent 10–15 minutes per case manually opening each system to piece together a borrower's repayment history, application status, related-party exposure, and CRM notes.\n\nWe built a unified, search-first portal that consolidates all source databases into a single interface. A global search (by HKID, phone, name, or loan number) returns a complete 360° borrower profile across 13 structured modules: application metadata, partakers and related entities, credit reference data, uploaded documents, mortgage collateral, income/DSR calculations, full loan history, approval records, repayment timeline, collection conditions, CRM interaction log, and OCA/write-off records.\n\nTechnically: Next.js frontend over a Supabase PostgreSQL database with JSONB module columns for schema flexibility. An ETL layer pulls from legacy SQL databases, APIs, Excel exports, and web interfaces on a configurable schedule, with identity resolution to match records across systems. Role-based access control restricts sensitive modules (approval details, write-off data) to authorised roles. All lookups, profile views, and sensitive data access are logged for compliance. An embedded DeepSeek-powered assistant generates on-demand case summaries grounded on the open borrower record.",
  },
  {
    id: "wilson-cpa",
    title: "Compliance Intelligence Workspace — LKKS CPA Limited",
    text: "LKKS CPA Limited needed to accelerate client onboarding and engagement review without reducing the rigour required in a regulated assurance practice. Reviews were slow because client risk, document completeness, and compliance flags lived across separate files with no unified view.\n\nWe built a purpose-designed internal workspace with HKID-based client search and a deterministic risk-scoring engine across 10 weighted factors: missing KYC documents (8 pts each), internal compliance flags (7 pts each), overseas exposure (9 pts), ownership structure complexity (Simple / Layered / Complex), sanctions screening status, PEP classification, dormant-but-active patterns, incomplete audit trail, late tax status, and escalated audit status. Clients scoring 60+ are classified Elevated Risk and surfaced immediately in the leadership dashboard.\n\nFor each client the system surfaces key strengths, specific concerns, structured compliance observations, and recommended next actions — all generated by a compliance-aware AI assistant that cites source records and enforces human review at every decision gate. The system deliberately avoids autonomous decisioning: every recommendation is framed as input for a professional reviewer, not a replacement for one.\n\nTechnically: Next.js 15 / React 19 / TypeScript on Vercel. The risk engine is deterministic and auditable — no black-box scoring. The AI assistant returns structured responses (heading, recommendation, confidence range, bullet analysis, mandatory review note) designed to fit inside an existing engagement workflow.",
  },
  {
    id: "methodology",
    title: "How both systems were delivered",
    text: "Both engagements followed the same delivery structure. We started with an operational audit: mapping every data source, handoff point, compliance boundary, and permission boundary before writing a line of code. The AI layer was designed around those constraints, not around what the model could theoretically do.\n\nIntegration was built on top of the client's existing systems rather than alongside them — no separate demo environment, no parallel data entry. Each system shipped with documented data flows, role permission matrices, audit log schemas, and a handoff package the client team could run without us.\n\nBoth systems are live and in daily operational use.",
  },
];

export function HomeServicesSection({ variant = "home" }: HomeServicesSectionProps) {
  const { dict } = useLocaleContext();
  const s = dict.services;

  return (
    <>
    <section
      id={variant === "home" ? "services" : undefined}
      className="relative overflow-hidden bg-[var(--background)] section-gutter"
    >
      <motion.div
        {...homeSectionReveal}
        transition={{ duration: 0.5 }}
        className="relative mx-auto flex h-full max-w-6xl flex-col justify-between gap-6 py-4 md:gap-10 md:py-10"
      >
        <div className="flex w-full flex-col justify-between gap-5 md:flex-row md:items-end md:gap-8">
          <div className="max-w-2xl">
            <p className="section-label mb-3">{s.sectionLabel}</p>
            <h2 className="text-[clamp(1.25rem,4.5vw,1.75rem)] leading-snug text-[var(--white-100)] md:text-3xl">
              {s.titleL1}
              <br />
              {s.titleL2}
            </h2>
          </div>
          <p className="max-w-md text-[0.8rem] leading-relaxed text-[var(--text-muted)] md:text-sm">
            {s.intro}
          </p>
        </div>

        <div className="w-full" aria-live="polite">
          <ServicesVoyageSlider services={s} />
        </div>
      </motion.div>
    </section>

    <section className="relative overflow-hidden bg-[var(--background)]">
      <FeatureShowcase
        className="bg-[var(--background)]"
        eyebrow="SELECTED PROJECTS"
        title="Two systems built around real operational constraints"
        description="A borrower intelligence portal consolidating five loan management databases for a Hong Kong lending firm, and a risk-scored compliance workspace for a CPA and assurance practice. Both are in daily production use."
        stats={["Hong Kong Financial Services", "CPA & Assurance", "AI-augmented"]}
        steps={projectSteps}
        tabs={selectedProjectTabs}
        defaultTab="grand-finance"
        panelMinHeight={720}
      />
    </section>
    </>
  );
}
