export const homeServices = [
  {
    label: "AI WORKFLOW AUDIT",
    title: "Find the best automation opportunity in one business process",
    duration: "1-2 weeks",
    scope: "Workflow review, bottlenecks, priority use case",
    body: "We review one team or process, identify where AI can remove friction fastest, and define the simplest high-value next step.",
    status: "Best for teams deciding where to start",
    id: "workflow-audit",
    bullets: ["Fast discovery", "Low commitment", "Clear implementation next step"],
  },
  {
    label: "INTERNAL KNOWLEDGE ASSISTANT",
    title: "Search and answer questions across documents and SOPs",
    duration: "2-4 weeks",
    scope: "Knowledge base, retrieval, internal assistant",
    body: "We build a lightweight internal assistant that helps teams find answers across company documents, guides, policies, and FAQs.",
    status: "Best for teams with fragmented internal knowledge",
    id: "knowledge-assistant",
    bullets: ["Fast employee answers", "Grounded on company docs", "Useful across teams"],
  },
  {
    label: "DOCUMENT AUTOMATION",
    title: "Extract, summarize, classify, and route business documents",
    duration: "2-5 weeks",
    scope: "PDFs, forms, email intake, structured outputs",
    body: "We automate repetitive document-heavy work such as intake, review, extraction, summarization, and routing for operations teams.",
    status: "Best for teams handling repetitive files and forms",
    id: "document-automation",
    bullets: ["Reduces manual review", "Structured outputs", "Works with existing workflows"],
  },
  {
    label: "CUSTOMER SUPPORT ASSISTANT",
    title: "Help support teams draft replies and retrieve the right context",
    duration: "2-4 weeks",
    scope: "Ticket support, knowledge retrieval, response drafts",
    body: "We create a practical support assistant that helps teams answer faster, summarize cases, and pull the right policy or account context.",
    status: "Best for teams with repeat support questions",
    id: "support-assistant",
    bullets: ["Faster support handling", "Consistent responses", "Human review stays in place"],
  },
] as const;
